services/ows.py
Use `ows` service config setting similar to that of `FrontierSI` and update inline with `GA` `ows` config settings.
=> Add ows service configuration for wofs and fractional cover

services/ows.py
**Following are the changes within this PR:**
1. Add `wcs_default_bands` to wofs 
2. Add `wofs` and `fractional cover` config settings as a separate products instead of combining within `Landsat 8`
=> Fix wcs_default_bands issue for wofs

products/ga_ls8c_wofs_2.yaml, products/ls_usgs_wofs_scene.yaml
Adding checks for bits 3,4 terrain shadow and high slope.
Make `wet|dry` flags match behaviour of wofs stats code here:
https://github.com/GeoscienceAustralia/wofs/blob/8f4d6da9c00cb21b21752bc91814995c05e3980f/wofs-summary/simple.py#L99-L116
That code checks all quality bits except for `sea` (bit `2`).
=> Only ignore `sea` bit for `wet|dry` flag

products/ga_ls8c_fc_2.yaml
On the advice of Leo, this should never have been "dead_veg". We have verified this incorrect alias came from the original FC code.
=> Change alias for NPV in FC

services/ows.py
It messes with extent generation and isn't well supported in datacube_ows
=> Change use_default_extent to False

services/ows_cfg.py
as it's not a valid CRS it stops update ranges from running correctly with the following error: 
`datacube.utils.geometry._base.InvalidCRSError: Not a valid CRS: 'EPSG:102022'`
=> Remove broken CRS

terria/africa.json
This PR sets the 
`tileErrorThresholdBeforeDisabling` parameter on catalog items for DE-Africa map to a higher than default value, this helps to mitigate the Terria Error box which gets thrown because of SPDY errors in the 2D view.
To test it out visit http://de-africa-20200612t091417.terria.io/#clean and you can drop the revised africa.json on it.
=> add tileErrorThresholdBeforeDisabling parameter to catalog items

products/ga_s2_clear_pixel_count.yml
Product spec for clear pixel count product, this was tested in collection2 db.
Data for it is currently here:
- `s3://deafrica-stats-processing/ga_s2_clear_pixel_count/v0.0.0/`
- https://s3.console.aws.amazon.com/s3/buckets/deafrica-stats-processing/ga_s2_clear_pixel_count/v0.0.0/?region=us-west-2&tab=overview
=> Add ga_s2_clear_pixel_count product definintion

products/ga_s2_clear_pixel_count.yml
We now compute clear mask with 2 pre-processing options
- Buffer with 5 pixels (`clear_0_5`)
- Shrink away small clouds (R=2) then buffer with 5 pixels (`clear_2_5`)
=> Add extra clear bands to clear pixel count product

products/ls5_sr.odc-product.yaml, products/ls5_st.odc-product.yaml, products/ls7_sr.odc-product.yaml, products/ls7_st.odc-product.yaml, products/ls8_sr.odc-product.yaml, products/ls8_st.odc-product.yaml
Split LS SR and ST into two products. SR include SR_ and QA_ bands. ST include ST_ and QA_ bands. Also updated alias to simply usage across the three LS and updated flags_definition to be more informative.
=> Split LS SR and ST

services/ows_refactored/radar_backscatter/ows_sentinel1_cfg.py
Could you please review the items in the Sentinel-1 OWS styling configuration file. 
I also need to get confirmation that 
"resource_limits": reslim_alos_palsar
will follow the same pattern as the ALOS dataset - reslim_alos_palsar follows SRTM in https://github.com/digitalearthafrica/config/blob/master/services/ows_refactored/common/ows_reslim_cfg.py
=> the configuration file for S1 styling

services/ows_refactored/surface_reflectance/band_sr_cfg.py, services/ows_refactored/surface_reflectance/ows_lsc2_sr_cfg.py, services/ows_refactored/surface_reflectance/ows_sr_cfg.py, services/ows_refactored/surface_reflectance/style_sr_cfg.py
Changed files:
* `style_sr_cfg.py`: 11 styles added for `lsc2_sr`, compiled in a new styles list `styles_lsc2_sr_list`. Scaling has been changed from 0-10000 to 1-65455 and existing ranges scaled accordingly
* `band_sr_cfg.py`: Common Landsat bands added to a new band list `bands_lsc2_sr` *note it is the same as the `bands_ls` list but so far has been separated so the old Landsat configs can be reorganised on a different occasion*
* `ows_sr_cfg.py`: "Collection 1" mentions upgraded to "Collection 2". "Five countries" replaced with "all Africa". Style and band list references updated to the new ones mentioned above
**To be added:** `ls_st` configs for surface temperature
Submitting the PR now for review. I expect some whitespace is causing issues but would like to check nothing else is.
=> OWS styles for Landsat C2 data

dev/alchemist/wofs_ls.alchemist.yaml
Additions to the lookup table for the colours of the quicklook when the cirrus is included.
- needed because with cirrus, shadow and cloud can occur at the same location
=> changes to lookup table for cirrus

services/ows_refactored/agriculture/ows_crop_mask_cfg.py, services/ows_refactored/elevation/ows_srtm_cfg.py, services/ows_refactored/elevation/ows_us_srtm_cfg.py, services/ows_refactored/pixel_count/ows_pc_ls_annual_cfg.py, services/ows_refactored/pixel_count/ows_pc_s2_annual_cfg.py, services/ows_refactored/radar_backscatter/ows_alos_cfg.py, services/ows_refactored/radar_backscatter/ows_jers_cfg.py, services/ows_refactored/radar_backscatter/ows_sentinel1_cfg.py, services/ows_refactored/radar_backscatter/ows_us_jers_cfg.py, services/ows_refactored/surface_reflectance/ows_geomedian_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_semiannual_cfg.py, services/ows_refactored/surface_reflectance/ows_lsc2_sr_cfg.py, services/ows_refactored/surface_reflectance/ows_s2_cfg.py, services/ows_refactored/surface_reflectance/ows_sr_cfg.py, services/ows_refactored/surface_temperature/ows_lsc2_st_cfg.py, services/ows_refactored/vegetation/ows_fc_cfg.py, services/ows_refactored/vegetation/ows_us_fc_cfg.py, services/ows_refactored/wofs/ows_wofs_cfg.py, services/ows_refactored/wofs/ows_wofs_ls_alltime_cfg.py, services/ows_refactored/wofs/ows_wofs_ls_annual_cfg.py, services/ows_refactored/wofs/ows_wofs_ls_cfg.py, services/ows_refactored/wofs/ows_wofsc2_cfg.py
For #248 
I have left the native CRS and resolution configured in the old and new places so we don't accidentally break production.
I had to change the native_crs from EPSG:4326 to EPSG:3857 for a bunch of layers.  If you specify EPSG:4326 then the native_resolution is expressed in degrees (not metres) and (30, -30) doesn't mean what it is supposed to mean.
=> Update native CRS and resolution entries.

services/ows_refactored/surface_reflectance/style_sr_cfg.py
@alexgleith here's an example of how to do it, using the same settings DEA C3.
I think DEA has it enabled for the `*ND*I` colour ramp styles.
=> Example Delta config.

services/ows_refactored/agriculture/ows_crop_mask_cfg.py, services/ows_refactored/elevation/ows_srtm_cfg.py, services/ows_refactored/elevation/ows_us_srtm_cfg.py, services/ows_refactored/radar_backscatter/ows_alos_cfg.py, services/ows_refactored/radar_backscatter/ows_jers_cfg.py, services/ows_refactored/radar_backscatter/ows_sentinel1_cfg.py, services/ows_refactored/radar_backscatter/ows_us_jers_cfg.py, services/ows_refactored/surface_reflectance/ows_geomedian_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_semiannual_cfg.py, services/ows_refactored/surface_reflectance/ows_lsc2_sr_cfg.py, services/ows_refactored/surface_reflectance/ows_s2_cfg.py, services/ows_refactored/surface_reflectance/ows_sr_cfg.py, services/ows_refactored/surface_temperature/ows_lsc2_st_cfg.py, services/ows_refactored/vegetation/ows_fc_cfg.py, services/ows_refactored/vegetation/ows_us_fc_cfg.py, services/ows_refactored/wofs/ows_wofs_cfg.py, services/ows_refactored/wofs/ows_wofs_ls_alltime_cfg.py, services/ows_refactored/wofs/ows_wofs_ls_annual_cfg.py, services/ows_refactored/wofs/ows_wofs_ls_cfg.py, services/ows_refactored/wofs/ows_wofsc2_cfg.py
Needed a cross-compatible config during transitional period for new native_crs/resolution configuration.
With the release of 1.8.16, we can cleanup the redundant config.
=> Remove redundant old-style native crs/resolution config.

services/ows_refactored/prod_af_ows_root_cfg.py
The `dev_layer` for S-2 GeoMAD works well in the ows.dev deployment.
PR to use this same dev_layer in production environment.
Can be tested at `ows-latest` before any tagged versions are released.
=> Retest deploying smart reslim to prod.

services/ows_refactored/common/ows_reslim_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_semiannual_cfg.py
- Edited smart_reslim6 to smart_reslim5
- Edited semiannuals (only) to use this 
This should improve mid-range data loading in Terria.
=> Semiannuals - reduced min zoom

.github/workflows/ows-config-test-build.yaml, .github/workflows/scripts/download-mo.py, .github/workflows/scripts/upload-po.py, README.md, docker-compose.ows.yaml, services/ows_refactored/prod_af_ows_root_cfg.py
This change adds translation for the OWS metadata catalog for the PROD config. 
On commit, uploads translatable terms to translation site POEditor.com.
On build/release of docker image, downloads latest compiled French translation file.
* Treats POEditor as the single point of truth for translation
* Does not track version translation file when releasing docker image
* Only set up for PROD, not DEV config
Requires `POEDITOR_API_TOKEN` to be added as a repo secret.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Ows translation

.github/workflows/ows-config-test-build.yaml, .github/workflows/scripts/download-mo.py, services/ows_refactored/prod_af_ows_root_cfg.py
Set the translation path to be `/env/config/ows_refactored/translations` on production deployment.
Also only uploads the `.po` file on master, PR and releases, to avoid rate limiting on POEditor.com.
=> Fix translations path

terria/africa-prod.json
Accidentally made Fractional cover the top menu heading instead of Vegetation. 
This PR fixes that and also removes one level of menu headings.
=> Corrected menu subheadings.

services/inventory/dev_af/inventory.json, services/inventory/prod_af/inventory.json, services/ows_refactored/vegetation/ows_fc_cfg.py
- Renamed `fc_ls` RGB styles to match other products
- Renamed style names
- Updated legend URLs to the `sandbox-notebook` repo
- Removed data.deafrica dead links
- Renamed relevant inventory style names
=> `fc_ls` style, inventory update

services/ows_refactored/wofs/ows_wofs_ls_alltime_cfg.py, services/ows_refactored/wofs/ows_wofs_ls_annual_cfg.py
`default_bands` config is deprecated in new ows release so removing it.
=> remove default_bands config - no longer required

services/ows_refactored/dev_af_ows_root_cfg.py
Adds french translation to dev ows.
Uses the prod translation, so only terms already in the prod config will be translated.
=> Add translation (of prod catalog) to dev ows

services/ows_refactored/surface_reflectance/style_sr_cfg.py, services/ows_refactored/vegetation/ows_fc_summary_annual_cfg.py
- This is not supported in new ows release - configure "legend" in `tick_labels` instead
=> remove legend elements in the color_ramp definition

products/ndvi_climatology_ls.odc-product.yaml
The datatype of the 'clear count' measurements in the NDVI climatology product was set to `int8`, which was not large enough for some of the pixels which had >128 observations. This PR will fix the dtype in the product definition for the clear count measurements.  
DO NOT MERGE: the data itself will need to be reprocessed, this PR is in anticipation of re-running the data in early 2022
=> Change dtype of count measurements in NDVI climatology

terria/africa-prod.json
Add
```json
"perLayerLinkedWcs": {
"linkedWcsUrl": "https://ows.digitalearth.africa/"
}
```
to the root WMS group. This enabled WCS/Export functionality for **all** WMS layers. This will use WMS `Layer.Name` as WCS `coverageId`. See https://github.com/TerriaJS/terriajs/pull/6108 for more info
https://maps.digitalearth.africa/#clean&https://raw.githubusercontent.com/digitalearthafrica/config/90d8c5045c500e70c80f6d78f0d00031c774a01e/terria/africa-prod.json
=> Add WCS/Export functionality to WMS layers

services/ows_refactored/wofs/style_wofs_ls_legacy.py
ows web conformance test is failing with below error so happing that this change fix it.
```
ERROR:root:Request to legend URL https://ows.dev.digitalearth.africa/legend/wofs_ls_summary_alltime/legacy_wofs_summary_alltime_frequency/legend.png 
for layer 'wofs_ls_summary_alltime', style 'legacy_wofs_summary_alltime_frequency' returned a non 200 status of 500 Server 
Error: Internal Server Error for url: https://ows.dev.digitalearth.africa/legend/wofs_ls_summary_alltime/legacy_wofs_summary_alltime_frequency/legend.png.  
WMS URL [https://ows.dev.digitalearth.africa,](https://ows.dev.digitalearth.africa%2C/) version 1.3.0.
```
=> enable show_legend for legacy_style_wofs_summary_alltime

geoserver/geoserver_data/collections/coastline_v0.3.0/styles/coastlines.sld
Some Coastlines annual shorelines are not currently plotting with dashed lines correctly. For example, here's a location in the Coastlines GeoPackage (top), and the same location in the GeoServer WMS (bottom):
My guess is that this is because the style includes a "Low quality shorelines" rule doesn't include the "stroke-dasharray" bit in the sections below, so that layer is being shown under all of the other data, making it look like the lines are solid.
e.g. this:
https://github.com/digitalearthafrica/config/blob/master/geoserver/geoserver_data/collections/coastline_v0.3.0/styles/coastlines.sld#L561-L566
v.s. this:
https://github.com/digitalearthafrica/config/blob/master/geoserver/geoserver_data/collections/coastline_v0.3.0/styles/coastlines.sld#L584-L591
This PR is a test at fixing this …
=> Attempt to fix missing dashed shorelines

geoserver/geoserver_data/collections/coastline_v0.3.0/styles/coastlines.sld, geoserver/geoserver_data/collections/coastline_v0.3.0/styles/coastlines_roc.sld, geoserver/geoserver_data/collections/coastline_v0.3.0/styles/coastlines_zoom_1.sld, geoserver/geoserver_data/collections/coastline_v0.3.0/styles/coastlines_zoom_2.sld, geoserver/geoserver_data/collections/coastline_v0.3.0/styles/coastlines_zoom_3.sld
This PR attempts to improve the appearance of uncertain coastlines in the Coastlines geoserver by expanding the dashes on these lines to make them more obvious.
Work in progress, do not merge
=> Styling updates to Coastlines geoserver

services/ows_refactored/surface_reflectance/ows_s2_cfg.py
A user reported pixel alignment issues from WCS2 requests against the s2_l2a layer: [datacube-ows#872](https://github.com/opendatacube/datacube-ows/issues/872)
This issue is due to the native resolution being configured to 30m pixels instead of 10m pixels.  Additionally EPSG:3857 (Web Mercator) was configured as the native CRS, instead of a more appropriate equal-area projection.
This PR fixes both issues.
=> More appropriate native CRS and resolution for Sentinel-2 daily layer.

geoserver/geoserver_data/collections/coastlines/styles/coastlines_v0.4.0_rates_of_change.sld
A very minor update to add sorting by certainty to the rates of change points. This puts the uncertain white points underneath the certain coloured points.
Before:
After:
=> Add certainty sorting to rates of change

services/ows_refactored/land_cover/ows_wsf_cfg_2015.py, services/ows_refactored/land_cover/ows_wsf_cfg_2019.py
The current colour used for the WSF 2015 and 2019 (a light brown) is very difficult to see over a basemap. Colour changed to a lighter grey for WSF 2015 and a daker grey for 2019.
=> Change WSF 2015&2019 colour to Grey
