services/ows.py
Add statistical summaries of the `WOfS` product  with the following layers:
- The count of clear observations
- The count of wet observations
- The percentage of wet observations over time
=> Add wofs summary

services/ows.py
- Group Landsat to single layer
- Remove unnecessary PQ usage in Landsat and WOfS 
- Change layer names 
- Group WOfS daily Observations and WOfS Summary to single layer 
- Remove PEP 8 errors 
- Fixes for rendering GetFeatureinfo requests
=> Refactoring wms cfg file for DEAfrica data 

terria/africa.json
Add filter by date back to services
Update getFeatureInfo template
=> Add filter by date update getFeatureInfo template

products/eo3_landsat_ard.odc-type.yaml, products/ga_ls8c_wofs_2.yaml, products/ls_usgs_wofs_scene.yaml, products/usgs-level2-collection2-sample.odc-product.yaml
Lets get this in the main branch
=> Usgs collection2

services/ows.py
:warning: Don't merge until the data has been indexed and ranges have been generated :warning:
=> add c2 wofs styles and terria config

services/ows.py
Updated config for wofs annual colours to match those used in Australia (these are different to those used in displaying an all-time summary)
=> Update WOfS annual colours

services/ows.py, terria/africa.json
using annual styles for both, stolen verbatim from dea
=> clear count styles for c2 wofs

services/ows.py
Workaround fix for getFeatureInfo not working. Paul is working on a fix in the code.
=> add in band definitions

services/ows_cfg.py
=> Ready for testing

services/ows_cfg.py
https://github.com/digitalearthafrica/config/issues/38
=> Fix wofs bands

services/ows_cfg.py
Reverts digitalearthafrica/config#51
=> Revert "Fix fractional cover legend"

services/ows_cfg.py
Reverts digitalearthafrica/config#60
=> Revert "Remove broken CRS"

terria/africa.json
Integrating Tessa's changes for DEAfrica map catalog structure and product names.
=> Adding latest catalog from Tessa

services/ows_cfg.py, terria/africa.json
Reverts digitalearthafrica/config#82
=> Revert "Sentinel"

services/ows_cfg.py
https://github.com/digitalearthafrica/config/pull/84/files
revert map masking change
=> revert ls_usgs_fc_scene masking change

products/ga_s2_gm.odc-product.yaml
Add a product definition for the new S-2 geomedian.
=> Add S-2 Geomedian product definition

services/ows_cfg.py
First part of #93   RVI requires some ows enhancements.
=> Fix existing ALOS styles as per #93

services/ows_cfg.py
For #93   
Requires https://github.com/opendatacube/datacube-ows/pull/449
=> Add ALOS Radar Veg Index - requires OWS PR#449

terria/africa.json
to be released after ows is ready
=> add s2 geomedian

services/ows_cfg.py
Gives better results across a handful of reference images covering a broad range of African climatic conditions.
=> Paul's hand-tweaking of TMAD scaling parameters for African conditions.

services/ows_cfg.py
=> Split TMAD from Geomedian.  Add count style to both.

dev/services/wps/ows/datacube-wps-config.yaml, dev/services/wps/ows/pywps.cfg
Adds a placeholder for the datacube WPS configuration files
=> Placeholder for datacube WPS configuration

.github/workflows/ows_cfg_linting.yaml, .github/workflows/ows_cfg_testing.yaml, services/ows_refactored/prod_af_ows_root_cfg.py, services/ows_refactored/prod_ows_root_cfg.py, services/ows_refactored/surface_reflectance/ows_geomedian_cfg.py, services/ows_refactored/surface_reflectance/ows_s2_cfg.py, services/ows_refactored/wofs/ows_wofs_cfg.py, services/ows_refactored/wofs/ows_wofsc2_cfg.py
- split linting from ows_cfg test to a separate action
- setup flake8 and sort testing for ows cfg
=> refactor ows_cfg check

dev/services/wps/ows/pywps.cfg
Fixes WPS configuration for S3
=> Fixes WPS config

products/crop_mask_eastern_product.yaml, products/crop_mask_product.yaml
use the new branch to add crop mask
=> use new branch for the product

.github/PULL_REQUEST_TEMPLATE/ows_cfg_pull_request_template.md, .github/PULL_REQUEST_TEMPLATE/product_pull_request_template.md, .github/PULL_REQUEST_TEMPLATE/terria_pull_request_template.md
- for easy and consistent PR review
=> add pr template

products/ls5_c2l2.odc-product.yaml, products/ls7_c2l2.odc-product.yaml, products/ls8_c2l2.odc-product.yaml
- New Product ls5_c2l2
- New Product ls7_c2l2
- New Product ls8_c2l2
=> New products usgs level2

.github/workflows/ows_cfg_testing.yaml, services/inventory/dev_af/inventory.json, services/ows_refactored/crop_mask/ows_crop_mask_cfg.py, services/ows_refactored/dev_af_ows_root_cfg.py
- setup ows cfg for dev instance
- setup crop mask ows layer
- setup ci testing for dev ows cfg
=> setup dev ows cfg

products/ls5_c2l2.odc-product.yaml, products/ls7_c2l2.odc-product.yaml, products/ls8_c2l2.odc-product.yaml
=> Fixed some units

services/ows_refactored/crop_mask/ows_crop_mask_cfg.py
=> update cropmask config

.github/PULL_REQUEST_TEMPLATE/ows_cfg.md, .github/PULL_REQUEST_TEMPLATE/product.md, .github/PULL_REQUEST_TEMPLATE/terria.md, README.md
- add italic to summary for pr template
- add how to use to README
- shorten pr template name for easy access
=> simplify pull request template

.github/workflows/docker-image.yml
=> Fix typo in docker-image.yml

products/ls5_c2l2.odc-product.yaml, products/ls7_c2l2.odc-product.yaml, products/ls8_c2l2.odc-product.yaml
I know I asked for all these aliases... it's very hard to keep them aligned.
=> Updated ls5/7/8 product configs to fix dtype and improve consistency.

services/inventory/prod_af/inventory.json, services/ows_refactored/prod_af_ows_root_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py
- include geomedian config in capetown prod ows
=> add geomedian to prod af

services/inventory/dev_af/inventory.json, services/inventory/prod_af/inventory.json, services/ows_refactored/dev_af_ows_root_cfg.py, services/ows_refactored/prod_af_ows_root_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py
=> merge tmad into gm base

services/ows_refactored/common/ows_util_tools.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py
Issue is that extent is calculated using a layer-wide function, called per used band.  And three bands (TMAD) need a different extent function to the other bands.
This is one possible approach - if this doesn't work, I have a couple of other options at least one of which should work.
=> Get extent masking working for both median and mad

services/inventory/dev_af/inventory.json, services/inventory/prod/inventory.json, services/inventory/prod_af/inventory.json, services/ows_refactored/common/ows_util_tools.py, services/ows_refactored/surface_reflectance/ows_geomedian_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py, services/ows_refactored/surface_reflectance/style_sr_cfg.py
- Geomedian - RGB
- Geomedian - SWIR, NIR, Green
- MADs 
- MADs (desert)
- NDVI
- NDWI
- MNDWI
- NDCI
- Blue
- Green
- Red
- Red edge 710
- Red edge 740
- Red edge 780
- NIR
- Narrow NIR
- SWIR 1610
- SWIR 2200
- Spectral MAD
- Euclidean MAD
- Bray-Curtis MAD
- Clear observation count
**For follow-up:** Adding numbers to SWIR, NIR, red edge bands to distinguish them
=> GeoMAD layer name edits

products/gm_s2_semiannual.odc-product.yaml
add semiannual product config for indexing. Almost same as annual one.
=> add semiannual product

products/alos_palsar_mosaic.odc-product.yaml, products/jers_sar_mosaic.odc-product.yaml
=> Update jers and alos mosaics to change int to uint where required

products/crop_mask_eastern.odc-product.yaml
add one more band into the crop_mask_eastern product
=> update the crop mask config

services/ows_refactored/surface_reflectance/style_sr_cfg.py
Just would like to check it is acceptable to set the URL as the S3 link: `"url": "s3://deafrica-services/gm_s2_annual/gm_s2_annual_legend.png"`
=> Added legend to MAD styles.

services/inventory/dev_af/inventory.json, services/inventory/prod_af/inventory.json, services/ows_refactored/elevation/ows_us_srtm_cfg.py, services/ows_refactored/prod_ows_root_cfg.py, services/ows_refactored/radar_backscatter/ows_alos_cfg.py, services/ows_refactored/radar_backscatter/ows_us_jers_cfg.py
Fixed products with different name in CT.
=> Update product names  in Cape Town

services/ows_refactored/surface_reflectance/band_sr_cfg.py, services/ows_refactored/surface_reflectance/ows_lsc2_sr_cfg.py
https://explorer.dev.digitalearth.africa/products/ls8_sr
https://explorer.dev.digitalearth.africa/products/ls7_sr
https://explorer.dev.digitalearth.africa/products/ls5_sr
=> LS C2 band mapping

terria/africa-us.json, terria/africa.json
Updated catalog to use ows-af only
=> Updated terria catalog for Cape Town

services/ows_refactored/prod_af_ows_root_cfg.py
update ows cape-town config domain
=> update ows cape-town config domain

dev/alchemist/DEAfrica_wofs_c2.yaml, dev/alchemist/wofs_ls.alchemist.yaml
Adding the yaml for WOfS using USGS collection 2 data. 
This works on the sandbox using `run-one` and `run-many` in alchemist.
=> WOfS Alchemist YAML for USGS Collection 2 Landsat

products/crop_mask_eastern.odc-product.yaml
=> minor change the data type

dev/alchemist/fc_ls.alchemist.yaml, products/fc_ls.odc_product.yaml
Adding the yamls for fractional cover for LandSat for alchemist and the ODC product.
=> Fractional Cover yamls

services/inventory/dev_af/inventory.json, services/ows_refactored/vegetation/ows_fc_cfg.py
=> Enable more FC Styles

products/pc_ls8_annual.odc-product.yaml
**draft:** define ls8 pixel count product definition
=> define ls8 pixel count product definition - draft

services/ows_refactored/common/ows_reslim_cfg.py, services/ows_refactored/surface_reflectance/ows_geomedian_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_semiannual_cfg.py
We might need to adjust the numbers a little, but this should be fine as a first pass.
Pre-requisite to increasing the number of allowed frames in an animation.
=> Apply smart resource limits.

prod/alchemist/fc_ls.alchemist.yaml, prod/alchemist/wofs_ls.alchemist.yaml
* Add WOfS and FC configs for Alchemist production run
=> Add WO and FC prod configs

services/ows_refactored/common/ows_reslim_cfg.py, services/ows_refactored/surface_reflectance/ows_geomedian_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_semiannual_cfg.py
I think these numbers should work better - but let's merge early on a weekday morning so we can keep an eye on the impact.
=> Second attempt at "smart" resource management for geomedian.

services/ows_refactored/surface_reflectance/ows_geomedian_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_semiannual_cfg.py
Still not working.  I'm going to have to test more systematically in dev.
=> Rollback second attempt at config mgmt.

services/ows_refactored/dev_af_ows_root_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py
This should only affect dev and let me look into why it's falling over.
=> resource management experiment in dev

services/ows_refactored/agriculture/ows_crop_mask_cfg.py
Minor changes to make clear the crop mask service is currently provisional and a short sentence explaining that in the parent blurb.
=> Edits to `crop_mask` parent heading and blurb.

README.md
For future reference. OWS URLs have been included if that is not problematic.
=> Added OWS details to README.

services/ows_refactored/agriculture/ows_crop_mask_cfg.py
=> Final changes for crop mask config.

dev/products_dev.csv, products/rainfall_chirps.odc-product.yaml
=> Add chirps rainfall

services/ows_refactored/common/ows_reslim_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_semiannual_cfg.py
- Added `smart_reslim6` 
- Changed `dev_layer` in semiannuals cfg to use this instead
=> Modified semiannuals resource limit config

services/inventory/dev_af/inventory.json, services/ows_refactored/dev_af_ows_root_cfg.py, services/ows_refactored/meteorology/ows_rainfall.py
Should look approximately like this
=> Add chirps monthly rainfall data

services/ows_refactored/dev_af_ows_root_cfg.py, services/ows_refactored/prod_af_ows_root_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_semiannual_cfg.py
- Renames dev_layer to layer in semiannuals cfg
- Removes obsolete old layer and zoom style
=> Remove dev layer

products/crop_mask_eastern.odc-product.yaml, products/crop_mask_western.odc-product.yaml, services/ows_refactored/agriculture/ows_crop_mask_cfg.py
=> Use CAPS for crop mask EPSG

dev/products_dev.csv, products/gm_ls8_annual.odc-product.yaml, products/gm_s2_annual.odc-product.yaml, products/gm_s2_semiannual.odc-product.yaml
* Fixes the number of pixels in S-2 summaries
* Adds Landsat 8 GM product
* Adds LS8 GM to products list
=> Add LS8 GM Product and fix S-2 product tile sizes

services/inventory/dev_af/inventory.json, services/ows_refactored/dev_af_ows_root_cfg.py, services/ows_refactored/surface_reflectance/band_sr_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_ls8_annual_cfg.py, services/ows_refactored/surface_reflectance/style_sr_cfg.py
- Added new layer config file for `gm_ls8`
- Added new bands list for `gm_ls8`
- Added new styles list for `gm_ls8`
To tweak after successful push to dev:
- Zoom factor - currently using `reslim5`, factor can be refined
- Band scaling - currently using S2 GeoMAD min/max for MADs, bands
=> LS8 GeoMAD OWS - Dev only

services/ows_refactored/surface_reflectance/ows_gm_ls8_annual_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py
- set S2 Annual GeoMAD to reslim_5 (to match semiannuals, for now)
- set LS8 Annual GeoMAD to reslim_srtm
=> GeoMAD zooms

services/inventory/dev_af/inventory.json, services/ows_refactored/common/ows_reslim_cfg.py, services/ows_refactored/dev_af_ows_root_cfg.py, services/ows_refactored/vegetation/ows_fc_summary_annual_cfg.py
* Add FC Summary style
* Not including sea mask... (todo...)
=> Add OWS Styles for FC Annual Summary

services/ows_refactored/agriculture/ows_crop_mask_cfg.py, services/ows_refactored/elevation/ows_srtm_cfg.py, services/ows_refactored/elevation/ows_us_srtm_cfg.py, services/ows_refactored/land_cover/ows_io_lulc_cfg.py, services/ows_refactored/meteorology/ows_rainfall.py, services/ows_refactored/radar_backscatter/ows_alos_cfg.py, services/ows_refactored/radar_backscatter/ows_jers_cfg.py, services/ows_refactored/radar_backscatter/ows_sentinel1_cfg.py, services/ows_refactored/radar_backscatter/ows_us_jers_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_ls8_annual_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_annual_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_s2_semiannual_cfg.py, services/ows_refactored/surface_reflectance/ows_lsc2_sr_cfg.py, services/ows_refactored/surface_reflectance/ows_s2_cfg.py, services/ows_refactored/surface_reflectance/ows_sr_cfg.py, services/ows_refactored/surface_temperature/ows_lsc2_st_cfg.py, services/ows_refactored/vegetation/ows_fc_cfg.py, services/ows_refactored/vegetation/ows_us_fc_cfg.py, services/ows_refactored/wofs/ows_wofs_ls_alltime_cfg.py, services/ows_refactored/wofs/ows_wofs_ls_annual_cfg.py, services/ows_refactored/wofs/ows_wofs_ls_cfg.py
=> Remove WCS default bands

services/ows_refactored/vegetation/ows_fc_summary_annual_cfg.py
* Rename 10/50/90 percentile styles
* Fix time resolution
=> Fix naming and time_resolution for FCP

services/ows_refactored/surface_reflectance/ows_gm_ls5_ls7_annual_cfg.py, services/ows_refactored/surface_reflectance/ows_gm_ls8_annual_cfg.py
* Add lowres product to LS8 GM
* Add lowres product to LS5/7 GM
=> Add lowres to ls8 and ls5&7

services/inventory/dev_af/inventory.json, services/ows_refactored/dev_af_ows_root_cfg.py, services/ows_refactored/vegetation/ows_gmw_cfg.py
=> Add mangrove style

terria/africa-prod.json
Added GMW item under "Vegetation". PR for lint checks.
=> GMW to Terria catalogue

dev/products_dev.csv, products/rainfall_chirps_daily.odc-product.yaml
=> Add chirps daily to dev

dev/alchemist/fc_ls.alchemist.yaml
* Includes fixes for USGS scaling and Coefficient application
=> Update FC dev to use latest code

prod/alchemist/fc_ls.alchemist.yaml
* Upgrade the config to use the new flag `clip_after_regression`
* Update the version from `1.0.0` to `1.1.0`
=> Upgrade FC to 1.1

docker-compose.ows.yaml, products/cci_landcover.odc-product.yaml, services/ows_refactored/land_cover/ows_cci_landcover_cfg.py
* Adds a bunch of minor classes and blows out the height of the legend!
=> Add more cci classes

dev/products_dev.csv, prod/products_prod.csv, products/ls9_sr.odc-product.yaml, products/ls9_st.odc-product.yaml
* Added LS9 product definitions
=> Add LS9 product definitions

prod/products_prod.csv, services/ows_refactored/vegetation/ows_ndvi_clim_cfg.py, services/ows_refactored/vegetation/styles_ndvi_clim.py
Plus a couple of OWS tweaks - but not adding NDVI climatology to OWS prod just yet.
=> Add NDVI clim to prod products list

services/inventory/dev_af/inventory.json, services/ows_refactored/vegetation/ows_ndvi_anom_cfg.py, services/ows_refactored/vegetation/styles_ndvi_anom.py
Testing style: transparent unless the anomaly is greater than 2 standard deviations
DEV only
=> NDVI anomaly styling

services/ows_refactored/elevation/ows_srtm_deriv_cfg.py
=> SRTM-deriv fix

terria/africa-prod.json
Trying the suggested methods one at a time.
=> Applies diffstyle to all children

dev/products_dev.csv
=> IO LULC 9 class

services/inventory/prod_af/inventory.json, services/ows_refactored/prod_af_ows_root_cfg.py
Added `srtm_deriv` layer to prod root config and inventory
=> SRTM deriv to prod

geoserver/geoserver_data/collections/coastlines/layergroups/DEAfrica_Coastlines.json, geoserver/geoserver_data/global/settings.json
Updated email and organization for geoserver;
Updated abstract for coastlines
#453
=> Updated contact information for geoserver

dev/products_dev.csv, products/landsat_c2l2_ar.odc-product.yaml
Hi @mickwelli could you please review. Thanks
=> AR product def for dev

products/landsat_c2l2_ar.odc-product.yaml
Hi @nanaboamah89 please review
=> Updated aliases

services/inventory/prod_af/inventory.json, services/ows_refactored/prod_af_ows_root_cfg.py
Add the Rolling GeoMAD to production.
Fixes # (issue) if applicable
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Add Rolling GeoMAD to prod

services/ows_refactored/land_cover/ows_wsf_cfg_2019.py, terria/africa-prod.json
Update africa-prod.json to add WSF 2015 and 2019 to Land Cover group in Maps
=> Add WSF 2015 and 2019 to Land Cover group

services/ows_refactored/land_cover/ows_wsf_cfg_2015.py, services/ows_refactored/land_cover/ows_wsf_cfg_2019.py
Changes to layer styling - use "values": [1] instead of "values": [255]
=> Edits to WSF layers to OWS

services/ows_refactored/land_cover/ows_wsf_cfg_2015.py, services/ows_refactored/land_cover/ows_wsf_cfg_2019.py, terria/africa-prod.json
Changed the native resolution back to degrees and Changes to layer styling - "values": [255]
=> Update to WSF layer on OWS

services/inventory/dev_af/inventory.json, services/inventory/prod_af/inventory.json, services/ows_refactored/dev_af_ows_root_cfg.py, services/ows_refactored/land_cover/ows_wsf_cfg_2015.py, services/ows_refactored/land_cover/ows_wsf_cfg_2019.py, services/ows_refactored/land_cover/ows_wsf_evolution_cfg.py, services/ows_refactored/prod_af_ows_root_cfg.py
- Add WSF Evolution to OWS Dev & Prod
- Change the WSF 2015 an d2019 layer colours from Grey to Brown
=> Add WSF Evolution to OWS Dev & Prod

terria/africa-prod.json
Reverts digitalearthafrica/config#512 - didn't solve issue on maps platform
=> Revert "Move waterbodies to surface water group without subgroup"

terria/africa-prod.json
Store waterbodies product under "Surface water - waterbodies" in Terria config
=> Rename waterbodies group in Terria config

services/ows_refactored/radar_backscatter/ows_alos_cfg.py, services/ows_refactored/radar_backscatter/ows_jers_cfg.py, services/ows_refactored/surface_reflectance/ows_s2_cfg.py, services/ows_refactored/vegetation/ows_fc_cfg.py
Updated broken links in ows abstracts to use deafrica docs page.
=> Ows url update

terria/africa-prod.json
Added planet basemap to terria config. And a few other minor updates.
=> Planet basemap

products/s2_l2a_c1.odc-product.yaml
Updating sentinel-2 l2a c1 config document based on changes in stac metadata. Assisted by configuration proposed in PR https://github.com/digitalearthafrica/config/pull/494
=> Sentinel 2 collection 1 product

products/s1-monthly-mosaic.odc-product.yaml
Rename product measurements from lowercase to uppercase for testing.
=> S1 monthly mosaic product update

.github/workflows/apply-geoserver-config-dev.yml, .github/workflows/apply-geoserver-config-prod.yml
New DB introduced for africapolis config. Adding the DB name environment variable to the apply config script.
=> Add geoserver db env var

terria/africa-prod.json
Reverts digitalearthafrica/config#553
=> Revert "Maps update"

products/s2_l2a_c1.odc-product.yaml
We need to add the offset of -1000 to s2_l2a_c1, I'll need some assistance with enacting this in odc etc.
=> Add offset to s2_l2a_c1.odc-product.yaml

dev/products_dev.csv, products/wqs_annual.odc-product.yaml
Product config for the annual water quality variables
=> Add wqs_annual product to dev
